spring:
  application:
    name: consumer-demo

eureka:
  client:
    service-url:
      # eureka服务地址
      defaultZone: http://localhost:10086/eureka
    # 获取服务地址列表间隔时间，默认30秒
    registry-fetch-interval-seconds: 30

# 默认情况下,feign的集成的hystrix是关闭的,需配置打开
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 1000 # 建立链接的超时时长
    ReadTimeout: 2000 # 读取超时时长
    # ribbon内部有重试机制, 一旦超时, 会自动重新发起请求, 不希望重试, 可以添加配置:
    MaxAutoRetries: 0 # 当前服务器的重试次数
    MaxAutoRetriesNextServer: 0 # 重试多少次服务
    OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 服务降级超时时间, 默认是1秒
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 10 # 熔断触发最小请求次数，默认值是20

