spring:
  application:
    name: consumer-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
  instance:
    # 服务失效时间, 默认90秒
    lease-expiration-duration-in-seconds: 10
    # 服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 10

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
