server:
  port: ${port:10086}

spring:
  application:
    name: eureka-server


eureka:
  client:
    service-url:
      # eureka服务地址, 如果是集群, 需要指定其他集群eureka地址
      defaultZone: http://localhost:10086/eureka
    # 若只有一个eureka服务, 不注册自己, 默认集群是true
    register-with-eureka: false
    # 只有一个eureka服务, 不拉取其他服务
    fetch-registry: false
  server:
    # 服务失效剔除时间间隔，默认60秒
    eviction-interval-timer-in-ms: 10000
    # 关闭自我保护模式（默认是打开的）
    enable-self-preservation: false